baseURL = "https://papeleriakon-tiki.com/"
languageCode = "es-es"
title = "Papelería KON-TIKI"
theme = "alpha-church"
publishDir = "papeleriakon-tiki.com"

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-188233011-1"

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Sobre nosotros"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 3

  # [[menu.main]]
  #   name = "Noticias"
  #   url = "/posts/noticias"
  #   parent = "Blog"
  #   weight = 2

  # [[menu.main]]
  #   name = "Manualidades"
  #   url = "/posts/manualidades"
  #   parent = "Blog"
  #   weight = 2

  [[menu.main]]
    name = "Contacto"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "KON-TIKI"
  subtitle = "Papelería y Bellas Artes"
  author = "Guillermo Caracuel"
  languageCode = "es" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = false

  customCSS = ["custom.css"]

  [params.banner]
    image = "img/banner.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "36.51004"
    longitude = "-4.87862"
    zoom = "17"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "formspree"
    confirm_page = "/contact_thanks"
    formspree_email="f/mjvpoend"


    [params.footer]
      copyright = ["Papelería KON-TIKI by [Guillermo Caracuel](//github.com/gcaracuel)"]

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
